### PR TITLE
install: display the nice error messages based on the error codes

### LINKED ISSUE #87: Use the bundled error messages with the jak-project release
We started bundling nice error messages with the jak-project release to centralize the source of truth for the error codes, they should be used if something goes wrong.

### PR DESCRIPTION
**Pull request by xTVaser**
Closes #87

### CODE REVIEW

File: src/lib/setup/setup.ts [hunk 1]
```diff
@@ -74,16 +75,21 @@ export async function extractAndValidateISO(
...
   if (output.code === 0) {
     return true;
   }
-  throw new Error(`Extractor exited with code: ${output.code}`);
+
+  const explaination = await resolveErrorCode(output.code);
+  if (explaination === undefined) {
+    throw new Error(`Extractor exited with unexpected code: ${output.code}`);
+  }
+  throw new Error(explaination);
```
Comment (trippjoe) [inline src/lib/setup/setup.ts:92]: You repeat this block a couple times so maybe it would be better off inside the `resolveErrorCode` function.

File: src/lib/setup/setup_errors.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+}
+
+let errorMetadata = new Map<string, ErrorCodeMetadataEntry>();
+
+export async function resolveErrorCode(
+  code: number
+): Promise<string | undefined> {
+  if (errorMetadata === undefined || errorMetadata.size == 0) {
+    // first time, load the metadata
+    const errorMetadataPath = `${await appDir()}data/launcher/error-code-metadata.json`;
```
Comment (trippjoe) [inline src/lib/setup/setup_errors.ts:23]: This is a bit ugly
