### PR TITLE
Fix clippy warnings

### LINKED ISSUE #244: Resolve Clippy Lints
Now that our repo is actually being linted, we should fix the issues.  There are about a hundred warnings that should be addressed as time permits https://github.com/open-goal/launcher/runs/14027688516

### PR DESCRIPTION
**Pull request by fabjan**
Mr. clips is now happy 🌮 closes #244.

The changes look huge because most of the Rust sources had CRLF line-endings.

The first commit just fixes all of those. If the PR changes are reviewed hiding whitespace changes they should not be visible.

I mostly only followed the advice of clippy.

hiding whitespace for review

### CODE REVIEW

File: src-tauri/src/textures.rs [hunk 1]
```diff
@@ -1,3 +1,6 @@
+// these commands are not yet used, allow dead code in this module
+#![allow(dead_code)]
+
```
Comment (fabjan) [inline src-tauri/src/textures.rs:3]: Perhaps this was a lazy choice, but they seem to be in development.

File: src-tauri/src/textures.rs [hunk 2]
```diff
@@ -21,19 +24,19 @@ pub async fn extract_textures(app_handle: tauri::AppHandle, textures_array: Vec<
...
-  //     match zip_extract::extract(Cursor::new(archive), &target_dir, true) {
-  //         Ok(_) => continue,
-  //         Err(err) => println!("{:?}", err),
-  //     }
-  // }
+  for path in textures_array {
+    println!(
+      "Not extracting (not yet implemented) texture pack to {}: {path:?}",
+      text_dir.display(),
+    );
```
Comment (fabjan) [inline src-tauri/src/textures.rs:31]: This was just a trick to use the variables and not have to comment it all out to avoid warnings.

File: src-tauri/src/textures.rs (hunk 1 above)
Comment (xTVaser) [reply src-tauri/src/textures.rs:3]: yeah this file is still in a draft state so silencing them is totally acceptable

**Review by xTVaser — APPROVED** [review]
